src/nintendo_gw_web_shop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()

urlpatterns    = patterns( '',
    ( r'^$', 'django.views.generic.simple.redirect_to', { 'url' : 'webshop' } ),
    ( r'^webshop/', include( 'webshop.urls' ) ),
    ( r'^admin/', include( admin.site.urls ) ),
)

src/nintendo_gw_web_shop/webshop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import settings
admin.autodiscover()


urlpatterns    = patterns( '',
    ( r'^$', 'webshop.views.root' ),
    ( r'^home/$', 'webshop.views.home' ),
    ( r'^home/category/(?P<type_id>\d+)/', 'webshop.views.category' ),
    ( r'^home/search$', 'webshop.views.search' ),
    ( r'^register/$', 'webshop.views.register' ),
    ( r'^login/$', 'webshop.views.login' ),
    ( r'^passwordreset/$', 'webshop.views.password_reset' ),
    ( r'^passwordreset/requestnewpassword/$', 'webshop.views.request_new_password' ), # Request new password
    ( r'^passwordreset/newpasswordrequested/$', 'webshop.views.new_password_requested' ), # New password requested
    ( r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name' : 'webshop/passwordreset/new_password.html',  'post_reset_redirect': '/webshop/passwordreset/newpasswordset/' } ), # New Password
    ( r'^passwordreset/newpasswordset/$', 'webshop.views.new_password_set' ), # New password set
    ( r'^logout/$', 'webshop.views.logout' ),
    ( r'^myaccount/$', 'webshop.views.myaccount' ),
    ( r'^myaccount/accountdetails/$', 'webshop.views.account_details' ),
    ( r'^myaccount/changepassword/$', 'webshop.views.change_password' ),
    ( r'^myaccount/addressbook/$', 'webshop.views.address_book' ),
    ( r'^myaccount/addressbook/new/$', 'webshop.views.address_book_new' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/edit/$', 'webshop.views.address_book_edit' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/delete/$', 'webshop.views.address_book_delete' ),
    ( r'^myaccount/completedorders/$', 'webshop.views.completed_orders' ),
    ( r'^admin/$', 'webshop.views.admin' ),
    ( r'^admin/paidorders/$', 'webshop.views.admin_paid_orders' ),
    ( r'^admin/deliveredorders/$', 'webshop.views.admin_delivered_orders' ),
    ( r'^admin/statistics/$', 'webshop.views.admin_statistics' ),
    ( r'^about/$', 'webshop.views.about' ),
    ( r'^credits/$', 'webshop.views.credits' ),
    ( r'^cart/$', 'webshop.views.cart' ),
    ( r'^cart/add/$', 'webshop.views.add_to_cart' ),
    ( r'^cart/update$', 'webshop.views.update_cart' ),  
    ( r'^cart/empty/$', 'webshop.views.empty_cart' ),
    ( r'^payment/pay$', 'webshop.views.payment_pay'),
    ( r'^payment/confirm$', 'webshop.views.payment_confirm'),
    ( r'^payment/success$', 'webshop.views.payment_success'),
    ( r'^payment/cancel$', 'webshop.views.payment_cancel'),
    ( r'^payment/error$', 'webshop.views.payment_error'),
    
    #Ajax urls
    ( r'^ajax/product/(?P<product_id>\d+)/rating/$', 'webshop.views.rating'),
    ( r'^ajax/product/(?P<product_id>\d+)/comment/$', 'webshop.views.comment'),
    ( r'^ajax/products/$', 'webshop.views.ajaxproducts'),
    ( r'^ajax/statistics/commentcount/$', 'webshop.views.ajaxstatisticscommentcount'),
    ( r'^ajax/product/(?P<product_id>\d+)/view/$', 'webshop.views.addproductview'),
    ( r'^ajax/product/view/$', 'webshop.views.productview'),
    ( r'^ajax/comment/(?P<comment_id>\d+)/delete/$', 'webshop.views.commentdelete'),

    # Static files
    ( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT } ),
)

src/nintendo_gw_web_shop/webshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, UserChangeForm, PasswordChangeForm
from django.forms import ModelForm
from webshop.models import Address


"""
Address form.

Author(s): Markku Laine
"""
class AddressForm( ModelForm ):
    class Meta:
        model                   = Address
        exclude                 = ( "user" )

    def __init__( self, *args, **kwargs ):
        super( AddressForm, self ).__init__( *args, **kwargs )
        # Override default error messages
        self.fields[ "streetAddressLine1" ].error_messages = { "required": "%s is required." % self.fields[ "streetAddressLine1" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "streetAddressLine1" ].label,self.fields[ "streetAddressLine1" ].max_length ) }
        self.fields[ "streetAddressLine2" ].error_messages = { "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "streetAddressLine2" ].label,self.fields[ "streetAddressLine2" ].max_length ) }
        self.fields[ "zipCode" ].error_messages = { "required": "%s is required." % self.fields[ "zipCode" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "zipCode" ].label,self.fields[ "zipCode" ].max_length ) }
        self.fields[ "city" ].error_messages = { "required": "%s is required." % self.fields[ "city" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "city" ].label,self.fields[ "city" ].max_length ) }
        self.fields[ "state" ].error_messages = { "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "state" ].label,self.fields[ "state" ].max_length ) }
        self.fields[ "country" ].error_messages = { "required": "%s is required." % self.fields[ "country" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "country" ].label,self.fields[ "country" ].max_length ) }
        self.fields[ "country" ].widget.attrs[ "readonly" ]  = True


"""
Authentication (login) form.

Author(s): Markku Laine
"""
class MyAuthenticationForm( AuthenticationForm ):
    username_label              = "Username"
    username_max_length         = 30
    password_label              = "Password"
    password_max_length         = 128
    username                    = forms.CharField( label="%s" % username_label, max_length="%d" % username_max_length, error_messages={ "required" : "%s is required." % username_label, "max_length" : "%s is too long, maximum length is %d." % ( username_label, username_max_length ) } )
    password                    = forms.CharField( label="%s" % password_label, max_length="%d" % password_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password_label, "max_length" : "%s is too long, maximum length is %d." % ( password_label, password_max_length ) })


"""
Password reset (forgot your password?) form.

Author(s): Markku Laine
"""
class MyPasswordResetForm( PasswordResetForm ):
    email_label                 = "E-mail address"
    email_max_length            = 128
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )


"""
Password change (change password) form.

Author(s): Markku Laine
"""
class MyPasswordChangeForm( PasswordChangeForm ):
    old_password_label          = "Old password"
    old_password_max_length     = 128
    new_password1_label         = "New password"
    new_password1_max_length    = 128
    new_password2_label         = "Confirm new password"
    new_password2_max_length    = 128
    old_password                = forms.CharField( label="%s" % old_password_label, max_length="%d" % old_password_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % old_password_label, "max_length" : "%s is too long, maximum length is %d." % ( old_password_label, old_password_max_length ) })
    new_password1               = forms.CharField( label="%s" % new_password1_label, max_length="%d" % new_password1_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % new_password1_label, "max_length" : "%s is too long, maximum length is %d." % ( new_password1_label, new_password1_max_length ) })
    new_password2               = forms.CharField( label="%s" % new_password2_label, max_length="%d" % new_password2_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % new_password2_label, "max_length" : "%s is too long, maximum length is %d." % ( new_password2_label, new_password2_max_length ) })


"""
User creation (register) form.

Author(s): Markku Laine
"""
class MyUserCreationForm( UserCreationForm ):
    first_name_label            = "First name"
    first_name_max_length       = 30
    last_name_label             = "Last name"
    last_name_max_length        = 30
    username_label              = "Username"
    username_max_length         = 30
    password1_label             = "Password"
    password1_max_length        = 128
    password2_label             = "Confirm password"
    password2_max_length        = 128
    email_label                 = "E-mail address"
    email_max_length            = 128
    first_name                  = forms.CharField( label="%s" % first_name_label, max_length="%d" % first_name_max_length, error_messages={ "required" : "%s is required." % first_name_label, "max_length" : "%s is too long, maximum length is %d." % ( first_name_label, first_name_max_length ) } )
    last_name                   = forms.CharField( label="%s" % last_name_label, max_length="%d" % last_name_max_length, error_messages={ "required" : "%s is required." % last_name_label, "max_length" : "%s is too long, maximum length is %d." % ( last_name_label, last_name_max_length ) } )
    username                    = forms.RegexField( label="%s" % username_label, max_length="%d" % username_max_length, regex=r"^[\w.@+-]+$", error_messages={ "required" : "%s is required." % username_label, "max_length" : "%s is too long, maximum length is %d." % ( username_label, username_max_length ), "invalid": "%s may contain only letters, numbers and @/./+/-/_ characters." % username_label } )
    password1                   = forms.CharField( label="%s" % password1_label, max_length="%d" % password1_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password1_label, "max_length" : "%s is too long, maximum length is %d." % ( password1_label, password1_max_length ) })
    password2                   = forms.CharField( label="%s" % password2_label, max_length="%d" % password2_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password2_label, "max_length" : "%s is too long, maximum length is %d." % ( password2_label, password2_max_length ) })
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )

    class Meta( UserCreationForm.Meta ):
        fields                  = ( "first_name", "last_name", "username", "password1", "password2", "email" )
    

"""
User change (account details) form.

Author(s): Markku Laine
"""
class MyUserChangeForm( UserChangeForm ):
    first_name_label            = "First name"
    first_name_max_length       = 30
    last_name_label             = "Last name"
    last_name_max_length        = 30
    email_label                 = "E-mail address"
    email_max_length            = 128
    first_name                  = forms.CharField( label="%s" % first_name_label, max_length="%d" % first_name_max_length, error_messages={ "required" : "%s is required." % first_name_label, "max_length" : "%s is too long, maximum length is %d." % ( first_name_label, first_name_max_length ) } )
    last_name                   = forms.CharField( label="%s" % last_name_label, max_length="%d" % last_name_max_length, error_messages={ "required" : "%s is required." % last_name_label, "max_length" : "%s is too long, maximum length is %d." % ( last_name_label, last_name_max_length ) } )
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )
    
    class Meta( UserChangeForm.Meta ):
        fields  = ( "username", "first_name", "last_name", "email" )
        
    def __init__( self, *args, **kwargs ):
        super( MyUserChangeForm, self ).__init__( *args, **kwargs )
        self.fields[ "username" ].widget.attrs[ "readonly" ]  = True
        #del self.fields[ "username" ] # This is a declared field we really want to be removed from the form to be rendered

src/nintendo_gw_web_shop/templates/webshop/passwordreset/new_password.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Password Reset - New Password{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Focus to the first input field
			$( "#id_new_password1" ).focus();

			// Validate the form
			$( "#password-reset-form" ).validate( {
				rules: {
					"new_password1": {
						required: true,
						maxlength: 128
					},
					"new_password2": {
						required: true,
						maxlength: 128,
						equalTo: "#id_new_password1"
					}
				},
				messages: {
					"new_password1": {
						required: "New password is required."
					},
					"new_password2": {
						required: "New password confirmation is required.",
						equalTo: "Please enter the same new password as above."
					}
				}
			} );
		} );
	</script>				
{% endblock %}
{% block page-title %}Password Reset{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>New Password</h3>
		{% if validlink %}
			<form id="password-reset-form" class="form" action="" method="post">
				{# Show validation errors #}
				{% if form.errors %}
					<div class="messages validation">
						<ul class="messages-list-validation">
							{% for key,value in form.errors.items %}
								{% for error in value %}<li>{{ error }}</li>{% endfor %} 
							{% endfor %}
						</ul>
					</div>
				{% endif %}
				{% load messages %}
				{% render_messages messages %}
				{% csrf_token %}
				<table>
					<tbody>
						{% for field in form %}
							<tr>
								<th>
									<label for="{{ field.auto_id }}">
										{% if field.field.required %}
											<span class="required">{{ field.label }}:</span>
										{% else %}
											{{ field.label }}:
										{% endif %}
									</label>
								</th>
								<td>{{ field }}</td>
							</tr>
						{% endfor %}
						<tr>
							<th>&nbsp;</th>
							<td><input type="submit" value="Change password" /></td>
						</tr>
					</tbody>
				</table>
			</form>
		{% else %}
			<p>The password reset link was invalid, possibly because it has already been used. Please, <a href="{% url webshop.views.request_new_password %}">request a new password</a> reset.</p>	
		{% endif %}
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/passwordreset/new_password_requested.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Password Reset - New Password Requested{% endblock %}
{% block extra-scripts %}{% endblock %}
{% block page-title %}Password Reset{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>New Password Requested</h3>
		<p>We have e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly.</p>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/passwordreset/new_password_set.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Password Reset - Password Reset Complete{% endblock %}
{% block extra-scripts %}{% endblock %}
{% block page-title %}Password Reset{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Password Reset Complete</h3>
		<p>Your password has been set. You may go ahead and <a href="{% url webshop.views.login %}">login</a> now.</p>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/passwordreset/request_new_password.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Password Reset - Request New Password{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Focus to the first input field
			$( "#id_email" ).focus();
			
			// Validate the form
			$( "#password-reset-form" ).validate( {
				rules: {
					"email": {
						required: true,
						email: true,
						maxlength: 128
					}
				},
				messages: {
					"email": {
						required: "E-mail address is required.",
						email: "Please enter a valid e-mail address."
		            }
				}
			} );
		} );	
	</script>				
{% endblock %}
{% block page-title %}Password Reset{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Request New Password</h3>
		<form id="password-reset-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				<tbody>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Request new password" /> or <a href="{% url webshop.views.login %}">Cancel</a></td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
{% endblock %}