src/nintendo_gw_web_shop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()

urlpatterns    = patterns( '',
    ( r'^$', 'django.views.generic.simple.redirect_to', { 'url' : 'webshop' } ),
    ( r'^webshop/', include( 'webshop.urls' ) ),
    ( r'^admin/', include( admin.site.urls ) ),
)

src/nintendo_gw_web_shop/webshop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import settings
admin.autodiscover()


urlpatterns    = patterns( '',
    ( r'^$', 'webshop.views.root' ),
    ( r'^home/$', 'webshop.views.home' ),
    ( r'^home/category/(?P<type_id>\d+)/', 'webshop.views.category' ),
    ( r'^home/search$', 'webshop.views.search' ),
    ( r'^register/$', 'webshop.views.register' ),
    ( r'^login/$', 'webshop.views.login' ),
    ( r'^passwordreset/$', 'webshop.views.password_reset' ),
    ( r'^passwordreset/requestnewpassword/$', 'webshop.views.request_new_password' ), # Request new password
    ( r'^passwordreset/newpasswordrequested/$', 'webshop.views.new_password_requested' ), # New password requested
    ( r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name' : 'webshop/passwordreset/new_password.html',  'post_reset_redirect': '/webshop/passwordreset/newpasswordset/' } ), # New Password
    ( r'^passwordreset/newpasswordset/$', 'webshop.views.new_password_set' ), # New password set
    ( r'^logout/$', 'webshop.views.logout' ),
    ( r'^myaccount/$', 'webshop.views.myaccount' ),
    ( r'^myaccount/accountdetails/$', 'webshop.views.account_details' ),
    ( r'^myaccount/changepassword/$', 'webshop.views.change_password' ),
    ( r'^myaccount/addressbook/$', 'webshop.views.address_book' ),
    ( r'^myaccount/addressbook/new/$', 'webshop.views.address_book_new' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/edit/$', 'webshop.views.address_book_edit' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/delete/$', 'webshop.views.address_book_delete' ),
    ( r'^myaccount/completedorders/$', 'webshop.views.completed_orders' ),
    ( r'^admin/$', 'webshop.views.admin' ),
    ( r'^admin/paidorders/$', 'webshop.views.admin_paid_orders' ),
    ( r'^admin/deliveredorders/$', 'webshop.views.admin_delivered_orders' ),
    ( r'^admin/statistics/$', 'webshop.views.admin_statistics' ),
    ( r'^about/$', 'webshop.views.about' ),
    ( r'^credits/$', 'webshop.views.credits' ),
    ( r'^cart/$', 'webshop.views.cart' ),
    ( r'^cart/add/$', 'webshop.views.add_to_cart' ),
    ( r'^cart/update$', 'webshop.views.update_cart' ),  
    ( r'^cart/empty/$', 'webshop.views.empty_cart' ),
    ( r'^payment/pay$', 'webshop.views.payment_pay'),
    ( r'^payment/confirm$', 'webshop.views.payment_confirm'),
    ( r'^payment/success$', 'webshop.views.payment_success'),
    ( r'^payment/cancel$', 'webshop.views.payment_cancel'),
    ( r'^payment/error$', 'webshop.views.payment_error'),
    
    #Ajax urls
    ( r'^ajax/product/(?P<product_id>\d+)/rating/$', 'webshop.views.rating'),
    ( r'^ajax/product/(?P<product_id>\d+)/comment/$', 'webshop.views.comment'),
    ( r'^ajax/products/$', 'webshop.views.ajaxproducts'),
    ( r'^ajax/statistics/commentcount/$', 'webshop.views.ajaxstatisticscommentcount'),
    ( r'^ajax/product/(?P<product_id>\d+)/view/$', 'webshop.views.addproductview'),
    ( r'^ajax/product/view/$', 'webshop.views.productview'),
    ( r'^ajax/comment/(?P<comment_id>\d+)/delete/$', 'webshop.views.commentdelete'),

    # Static files
    ( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT } ),
)

src/nintendo_gw_web_shop/webshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, UserChangeForm, PasswordChangeForm
from django.forms import ModelForm
from webshop.models import Address


"""
Address form.

Author(s): Markku Laine
"""
class AddressForm( ModelForm ):
    class Meta:
        model                   = Address
        exclude                 = ( "user" )

    def __init__( self, *args, **kwargs ):
        super( AddressForm, self ).__init__( *args, **kwargs )
        # Override default error messages
        self.fields[ "streetAddressLine1" ].error_messages = { "required": "%s is required." % self.fields[ "streetAddressLine1" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "streetAddressLine1" ].label,self.fields[ "streetAddressLine1" ].max_length ) }
        self.fields[ "streetAddressLine2" ].error_messages = { "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "streetAddressLine2" ].label,self.fields[ "streetAddressLine2" ].max_length ) }
        self.fields[ "zipCode" ].error_messages = { "required": "%s is required." % self.fields[ "zipCode" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "zipCode" ].label,self.fields[ "zipCode" ].max_length ) }
        self.fields[ "city" ].error_messages = { "required": "%s is required." % self.fields[ "city" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "city" ].label,self.fields[ "city" ].max_length ) }
        self.fields[ "state" ].error_messages = { "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "state" ].label,self.fields[ "state" ].max_length ) }
        self.fields[ "country" ].error_messages = { "required": "%s is required." % self.fields[ "country" ].label, "max_length" : "%s is too long, maximum length is %d." % ( self.fields[ "country" ].label,self.fields[ "country" ].max_length ) }
        self.fields[ "country" ].widget.attrs[ "readonly" ]  = True


"""
Authentication (login) form.

Author(s): Markku Laine
"""
class MyAuthenticationForm( AuthenticationForm ):
    username_label              = "Username"
    username_max_length         = 30
    password_label              = "Password"
    password_max_length         = 128
    username                    = forms.CharField( label="%s" % username_label, max_length="%d" % username_max_length, error_messages={ "required" : "%s is required." % username_label, "max_length" : "%s is too long, maximum length is %d." % ( username_label, username_max_length ) } )
    password                    = forms.CharField( label="%s" % password_label, max_length="%d" % password_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password_label, "max_length" : "%s is too long, maximum length is %d." % ( password_label, password_max_length ) })


"""
Password reset (forgot your password?) form.

Author(s): Markku Laine
"""
class MyPasswordResetForm( PasswordResetForm ):
    email_label                 = "E-mail address"
    email_max_length            = 128
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )


"""
Password change (change password) form.

Author(s): Markku Laine
"""
class MyPasswordChangeForm( PasswordChangeForm ):
    old_password_label          = "Old password"
    old_password_max_length     = 128
    new_password1_label         = "New password"
    new_password1_max_length    = 128
    new_password2_label         = "Confirm new password"
    new_password2_max_length    = 128
    old_password                = forms.CharField( label="%s" % old_password_label, max_length="%d" % old_password_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % old_password_label, "max_length" : "%s is too long, maximum length is %d." % ( old_password_label, old_password_max_length ) })
    new_password1               = forms.CharField( label="%s" % new_password1_label, max_length="%d" % new_password1_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % new_password1_label, "max_length" : "%s is too long, maximum length is %d." % ( new_password1_label, new_password1_max_length ) })
    new_password2               = forms.CharField( label="%s" % new_password2_label, max_length="%d" % new_password2_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % new_password2_label, "max_length" : "%s is too long, maximum length is %d." % ( new_password2_label, new_password2_max_length ) })


"""
User creation (register) form.

Author(s): Markku Laine
"""
class MyUserCreationForm( UserCreationForm ):
    first_name_label            = "First name"
    first_name_max_length       = 30
    last_name_label             = "Last name"
    last_name_max_length        = 30
    username_label              = "Username"
    username_max_length         = 30
    password1_label             = "Password"
    password1_max_length        = 128
    password2_label             = "Confirm password"
    password2_max_length        = 128
    email_label                 = "E-mail address"
    email_max_length            = 128
    first_name                  = forms.CharField( label="%s" % first_name_label, max_length="%d" % first_name_max_length, error_messages={ "required" : "%s is required." % first_name_label, "max_length" : "%s is too long, maximum length is %d." % ( first_name_label, first_name_max_length ) } )
    last_name                   = forms.CharField( label="%s" % last_name_label, max_length="%d" % last_name_max_length, error_messages={ "required" : "%s is required." % last_name_label, "max_length" : "%s is too long, maximum length is %d." % ( last_name_label, last_name_max_length ) } )
    username                    = forms.RegexField( label="%s" % username_label, max_length="%d" % username_max_length, regex=r"^[\w.@+-]+$", error_messages={ "required" : "%s is required." % username_label, "max_length" : "%s is too long, maximum length is %d." % ( username_label, username_max_length ), "invalid": "%s may contain only letters, numbers and @/./+/-/_ characters." % username_label } )
    password1                   = forms.CharField( label="%s" % password1_label, max_length="%d" % password1_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password1_label, "max_length" : "%s is too long, maximum length is %d." % ( password1_label, password1_max_length ) })
    password2                   = forms.CharField( label="%s" % password2_label, max_length="%d" % password2_max_length, widget=forms.PasswordInput, error_messages={ "required" : "%s is required." % password2_label, "max_length" : "%s is too long, maximum length is %d." % ( password2_label, password2_max_length ) })
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )

    class Meta( UserCreationForm.Meta ):
        fields                  = ( "first_name", "last_name", "username", "password1", "password2", "email" )
    

"""
User change (account details) form.

Author(s): Markku Laine
"""
class MyUserChangeForm( UserChangeForm ):
    first_name_label            = "First name"
    first_name_max_length       = 30
    last_name_label             = "Last name"
    last_name_max_length        = 30
    email_label                 = "E-mail address"
    email_max_length            = 128
    first_name                  = forms.CharField( label="%s" % first_name_label, max_length="%d" % first_name_max_length, error_messages={ "required" : "%s is required." % first_name_label, "max_length" : "%s is too long, maximum length is %d." % ( first_name_label, first_name_max_length ) } )
    last_name                   = forms.CharField( label="%s" % last_name_label, max_length="%d" % last_name_max_length, error_messages={ "required" : "%s is required." % last_name_label, "max_length" : "%s is too long, maximum length is %d." % ( last_name_label, last_name_max_length ) } )
    email                       = forms.EmailField( label="%s" % email_label, max_length="%d" % email_max_length, error_messages={ "required" : "%s is required." % email_label, "max_length" : "%s is too long, maximum length is %d." % ( email_label, email_max_length ) } )
    
    class Meta( UserChangeForm.Meta ):
        fields  = ( "username", "first_name", "last_name", "email" )
        
    def __init__( self, *args, **kwargs ):
        super( MyUserChangeForm, self ).__init__( *args, **kwargs )
        self.fields[ "username" ].widget.attrs[ "readonly" ]  = True
        #del self.fields[ "username" ] # This is a declared field we really want to be removed from the form to be rendered

src/nintendo_gw_web_shop/templates/webshop/about.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - About{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#footer-navi-about>span" ).addClass( "footer-navi-selected" );
		} );
	</script>				
{% endblock %}
{% block page-title %}About{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>About</h3>
		<p>Nintendo Game &amp; Watch Shop is a school project for a course called <a href="https://noppa.tkk.fi/noppa/kurssi/t-106.4300/">T-106.4300 Web Software Development (3-6 cr)</a>, which is held at the <a href="http://information.tkk.fi/fi/">Aalto University School of Science</a>.</p>
		<p>The project was done by the following students:</p>
		<ul>
			<li>Markku Laine</li>
			<li>Juha Loukkola</li>
			<li>Kalle Säilä</li>
		</ul>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/account.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Profile{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript" src="/webshop/static/js/jquery.validate.min.js"></script>
	<script type="text/javascript">
		$( function() {
			$( "#navi-account>span" ).addClass( "navi-selected" );
			
			$( "#profile-form" ).validate( {
				rules: {
					"first_name": {
						required: true,
						maxlength: 30
					},
					"last_name": {
						required: true,
						maxlength: 30
					},
					"email": {
						required: true,
						email: true,
						maxlength: 128
					}
				},
				messages: {
					"first_name": {
						required: "First name is required."
					},
					"last_name": {
						required: "Last name is required."
					},
					"email": {
						required: "E-mail address is required.",
						email: "Please enter a valid e-mail address."
		            }
				}
			} );
		} );	
	</script>				
{% endblock %}
{% block page-title %}Profile{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Profile</h3>
		<form id="profile-form" class="form" action="{% url webshop.views.account %}" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				{% for field in form %}
					<tr>
						<th>
							<label for="{{ field.auto_id }}">
								{% if field.field.required %}
									<span class="required">{{ field.label }}</span>
								{% else %}
									{{ field.label }}
								{% endif %}
							</label>
						</th>
						<td>{{ field }}</td>
					</tr>
				{% endfor %}
				<tr>
					<th>&nbsp;</th>
					<td><input type="submit" value="Save" /></td>
				</tr>
			</table>
		</form>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/base_template.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="utf-8" />
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="/webshop/static/css/style.css?{% now "U" %}" />
		<script type="text/javascript" src="/webshop/static/js/modernizr-1.5.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
		<script type="text/javascript" src="/webshop/static/js/jquery.validate.min.js"></script>
		<!--[if IE]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		{% block extra-scripts %}{% endblock %}
		<script type="text/javascript">
			$(function() {
				$('#search-button').click(function(){
					window.location.href = 'http://' + location.host +'/webshop/home/search?q=' + $('#search-input').val();
				});
				$('#search-input').focusin(function() {
					$(this).val('');
				});
				var tags;
				$.getJSON('/webshop/ajax/products', function(data) {
					tags = data;
					$( "#search-input" ).autocomplete({
		       			source: tags,
		       			minLength: 2,
		       			focus: function( event, ui ) {
		    				$( "#search-input" ).val( ui.item.label );
		    				return false;
		    			},
		    			select: function( event, ui ) {
		    				$( "#search-input" ).val( ui.item.label );
							window.location.href  = 'http://' + location.host +'/webshop/home/category/'+ui.item.type+'/product#item'+ui.item.id;
		    				return false;
		    			}
		       		});
				});
	       		
			});	
		</script>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<div id="logo">
					<a href="{% url webshop.views.home %}"><img src="/webshop/static/images/ngws_logo.png" /></a>
				</div>
				<div id="navi">
					<ul>
						<li><a id="navi-home" href="{% url webshop.views.home %}"><span>home</span></a></li>
						{% if user.is_authenticated %}
							<li><a id="navi-myaccount" href="{% url webshop.views.account_details %}"><span>my account</span></a></li>
							{% if user.is_staff %}
								<li><a id="navi-admin" href="{% url webshop.views.admin_paid_orders %}"><span>admin</span></a></li>
							{% endif %}
							<li><a id="navi-logout" href="{% url webshop.views.logout %}"><span>logout</span></a></li>
						{% else %}
							<li><a id="navi-register" href="{% url webshop.views.register %}"><span>register</span></a></li>
							<li><a id="navi-login" href="{% url webshop.views.login %}"><span>login</span></a></li>
						{% endif %}	
						<li><a id="navi-cart" href="{% url webshop.views.cart %}"><span>cart (<span id="cart-span">{% if request.session.numberOfCartItems %}{{ request.session.numberOfCartItems }}{% else %}0{% endif %}</span>)</span></a></li>
					</ul>
				</div>
				<div id="search-bar">
					<form action="/webshop/home/search" method="get"><input id="search-input" value="Search" name="q"/><input type="button" id="search-button" value="&nbsp;"/><input type="submit" id="search-submit" value="&nbsp;"/></form>
				</div>
				<h3 id="page-title">{% block page-title %}{% endblock %}</h3>
				{% block sort-bar %}{% endblock %}
			</div>
			<div id="content">
				{% block content %}{% endblock %}
			</div>
			<div id="footer">
				<div id="footer-navi">
					<ul>
						<li><a id="footer-navi-about" href="{% url webshop.views.about %}"><span>about</span></a></li>
						<li><a id="footer-navi-credits" href="{% url webshop.views.credits %}"><span>credits</span></a></li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>

src/nintendo_gw_web_shop/templates/webshop/credits.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Credits{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#footer-navi-credits>span" ).addClass( "footer-navi-selected" );
		} );
	</script>				
{% endblock %}
{% block page-title %}Credits{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Credits</h3>
		<ul>
			<li><a href="https://github.com/mrben/nicer_django_messages_output">Nicer Django Messages Output</a></li>		
			<li><a href="http://mpanayiotakis.proboards.com/index.cgi">Mike&apos;s Nintendo game&amp;watch forum - FAQ</a></li>
			<li><a href="http://www.highcharts.com/">Highcharts JS</a></li>	
			<li><a href="http://razorjack.net/quicksand/">Quicksand</a></li>
			<li><a href="http://lab.smashup.it/flip/">Flip!</a></li>
			<li><a href="http://www.mudaimemo.com/p/simpledialog/">jQuery Simple Dialog</a></li>		
		</ul>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/forgot_your_password.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Login - Forgot Your Password?{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-login>span" ).addClass( "navi-selected" );

			// Focus to the first input field
			$( "#id_email" ).focus();
			
			// Validate the form
			$( "#forgot-your-password-form" ).validate( {
				rules: {
					"email": {
						required: true,
						email: true,
						maxlength: 128
					}
				},
				messages: {
					"email": {
						required: "E-mail address is required.",
						email: "Please enter a valid e-mail address."
		            }
				}
			} );
		} );	
	</script>				
{% endblock %}
{% block page-title %}Login{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Forgot Your Password?</h3>
		<form id="forgot-your-password-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				<tbody>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Reset password" /> or <a href="{% url webshop.views.login %}">Cancel</a></td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/register.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - Register{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-register>span" ).addClass( "navi-selected" );

			// Focus to the first input field
			$( "#id_first_name" ).focus();

			// Validate the form
			$( "#register-form" ).validate( {
				rules: {
					"first_name": {
						required: true,
						maxlength: 30
					},
					"last_name": {
						required: true,
						maxlength: 30
					},
					"username": {
						required: true,
						maxlength: 30
					},
					"password1": {
						required: true,
						maxlength: 128
					},
					"password2": {
						required: true,
						maxlength: 128,
						equalTo: "#id_password1"
					},
					"email": {
						required: true,
						email: true,
						maxlength: 128
					},
					"streetAddressLine1": {
						required: true,
						maxlength: 100
					},
					"streetAddressLine2": {
						maxlength: 100
					},
					"zipCode": {
						required: true,
						maxlength: 10
					},
					"city": {
						required: true,
						maxlength: 50
					},
					"state": {
						maxlength: 50
					},
					"country": {
						required: true,
						maxlength: 50
					}
				},
				messages: {
					"first_name": {
						required: "First name is required."
					},
					"last_name": {
						required: "Last name is required."
					},
					"username": {
						required: "Username is required."
					},
					"password1": {
						required: "Password is required."
					},
					"password2": {
						required: "Password confirmation is required.",
						equalTo: "Please enter the same password as above."
					},
					"email": {
						required: "E-mail address is required.",
						email: "Please enter a valid e-mail address."
		            },
					"streetAddressLine1": {
						required: "Street address line 1 is required."
					},
					"zipCode": {
						required: "ZIP code is required."
					},
					"city": {
						required: "City is required."
					},
					"country": {
						required: "Country is required."
					}
				}
			} );
		} );	
	</script>				
{% endblock %}
{% block page-title %}Register{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
	</div>
	<div id="main-content">
		<h3>Register</h3>
		<form id="register-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors or addressForm.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
						{% for key,value in addressForm.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<input type="hidden" name="next" value="{{ next }}" />
			<table id="register-table">
				<tbody>
					<tr>
						<th colspan="2">Basic Information</th>
					</tr>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr class="fieldset-separator">
						<th>&nbsp;</th>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<th colspan="2">Shipping Address</th>
					</tr>
					{% for field in addressForm %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Register" /></td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
{% endblock %}