src/nintendo_gw_web_shop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()

urlpatterns    = patterns( '',
    ( r'^$', 'django.views.generic.simple.redirect_to', { 'url' : 'webshop' } ),
    ( r'^webshop/', include( 'webshop.urls' ) ),
    ( r'^admin/', include( admin.site.urls ) ),
)

src/nintendo_gw_web_shop/webshop/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import settings
admin.autodiscover()


urlpatterns    = patterns( '',
    ( r'^$', 'webshop.views.root' ),
    ( r'^home/$', 'webshop.views.home' ),
    ( r'^home/category/(?P<type_id>\d+)/', 'webshop.views.category' ),
    ( r'^home/search$', 'webshop.views.search' ),
    ( r'^register/$', 'webshop.views.register' ),
    ( r'^login/$', 'webshop.views.login' ),
    ( r'^passwordreset/$', 'webshop.views.password_reset' ),
    ( r'^passwordreset/requestnewpassword/$', 'webshop.views.request_new_password' ), # Request new password
    ( r'^passwordreset/newpasswordrequested/$', 'webshop.views.new_password_requested' ), # New password requested
    ( r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name' : 'webshop/passwordreset/new_password.html',  'post_reset_redirect': '/webshop/passwordreset/newpasswordset/' } ), # New Password
    ( r'^passwordreset/newpasswordset/$', 'webshop.views.new_password_set' ), # New password set
    ( r'^logout/$', 'webshop.views.logout' ),
    ( r'^myaccount/$', 'webshop.views.myaccount' ),
    ( r'^myaccount/accountdetails/$', 'webshop.views.account_details' ),
    ( r'^myaccount/changepassword/$', 'webshop.views.change_password' ),
    ( r'^myaccount/addressbook/$', 'webshop.views.address_book' ),
    ( r'^myaccount/addressbook/new/$', 'webshop.views.address_book_new' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/edit/$', 'webshop.views.address_book_edit' ),
    ( r'^myaccount/addressbook/(?P<address_id>\d+)/delete/$', 'webshop.views.address_book_delete' ),
    ( r'^myaccount/completedorders/$', 'webshop.views.completed_orders' ),
    ( r'^admin/$', 'webshop.views.admin' ),
    ( r'^admin/paidorders/$', 'webshop.views.admin_paid_orders' ),
    ( r'^admin/deliveredorders/$', 'webshop.views.admin_delivered_orders' ),
    ( r'^admin/statistics/$', 'webshop.views.admin_statistics' ),
    ( r'^about/$', 'webshop.views.about' ),
    ( r'^credits/$', 'webshop.views.credits' ),
    ( r'^cart/$', 'webshop.views.cart' ),
    ( r'^cart/add/$', 'webshop.views.add_to_cart' ),
    ( r'^cart/update$', 'webshop.views.update_cart' ),  
    ( r'^cart/empty/$', 'webshop.views.empty_cart' ),
    ( r'^payment/pay$', 'webshop.views.payment_pay'),
    ( r'^payment/confirm$', 'webshop.views.payment_confirm'),
    ( r'^payment/success$', 'webshop.views.payment_success'),
    ( r'^payment/cancel$', 'webshop.views.payment_cancel'),
    ( r'^payment/error$', 'webshop.views.payment_error'),
    
    #Ajax urls
    ( r'^ajax/product/(?P<product_id>\d+)/rating/$', 'webshop.views.rating'),
    ( r'^ajax/product/(?P<product_id>\d+)/comment/$', 'webshop.views.comment'),
    ( r'^ajax/products/$', 'webshop.views.ajaxproducts'),
    ( r'^ajax/statistics/commentcount/$', 'webshop.views.ajaxstatisticscommentcount'),
    ( r'^ajax/product/(?P<product_id>\d+)/view/$', 'webshop.views.addproductview'),
    ( r'^ajax/product/view/$', 'webshop.views.productview'),
    ( r'^ajax/comment/(?P<comment_id>\d+)/delete/$', 'webshop.views.commentdelete'),

    # Static files
    ( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT } ),
)

src/nintendo_gw_web_shop/webshop/models.py
from django.contrib.auth.models import User
from django.db import models


"""
Types (categories) of products (games).

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""
class Type( models.Model ):
	name 							= models.CharField( max_length=50, unique=True )
	IMAGE_UPLOAD_TO					= "images/types"
	image							= models.ImageField( upload_to=IMAGE_UPLOAD_TO, max_length=255 )
	# Image thumbnail could have been left out if the thumbnail had been automatically generated. In our case, we had already done the thumbnails manually in advance
	imageThumb						= models.ImageField( "Image thumb", upload_to=IMAGE_UPLOAD_TO + "/thumbs", max_length=255 )
	
	def __unicode__( self ):
		return self.name + " series"
	__unicode__.short_description	= "Type"

	
	def firstproduct(self):
		prod = Product.objects.filter(type=self).order_by( "title" )
		return prod[0].id

"""
Products (games).

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""
class Product( models.Model ):
	title							= models.CharField( max_length=50 )
	type							= models.ForeignKey( Type )
	model							= models.CharField( max_length=20 )
	dateOfRelease					= models.DateField( "Date of release" )
	produced						= models.IntegerField( default=0 )
	RARITY_VERY_COMMON				= 1
	RARITY_COMMON					= 2
	RARITY_RARE						= 3
	RARITY_VERY_RARE				= 4
	RARITY_EXTREMELY_RARE			= 5
	RARITY_CHOICES	= (
		( RARITY_VERY_COMMON, "Very common" ),
		( RARITY_COMMON, "Common" ),
		( RARITY_RARE, "Rare" ),
		( RARITY_VERY_RARE, "Very rare" ),
		( RARITY_EXTREMELY_RARE, "Extremely rare" ),
	)
	rarity							= models.IntegerField( choices=RARITY_CHOICES )
	description						= models.TextField()
	quantity						= models.IntegerField( default=0 )
	IMAGE_UPLOAD_TO					= "images/products"
	image							= models.ImageField( upload_to=IMAGE_UPLOAD_TO, max_length=255 )
	# Image thumbnail could have been left out if the thumbnail had been automatically generated. In our case, we had already done the thumbnails manually in advance
	imageThumb						= models.ImageField( "Image thumb", upload_to=IMAGE_UPLOAD_TO + "/thumbs", max_length=255 )
	
	class Meta:
		ordering = ['title']

	def average( self ):
		result						= 0
		index						= 0
		for temp in self.rating_set.all():
			result					+= temp.rate
			index					+= 1
		if result > 0:
			return ( result / index )
		else:
			return result
		
	def dummylist( self ):
		my_list						= [ 1, 2, 3, 4, 5 ]
		return my_list
	
	def filteredcomments( self ):
		result_list					= []
		firstlayer					= self.comment_set.filter( commentsOn=None )

		for x in firstlayer:
			result_list.append(x)
			temp_list_1				= self.comment_set.filter( commentsOn=x )

			for y in temp_list_1:
				result_list.append(y)
				temp_list_2			= self.comment_set.filter( commentsOn=y )

				for z in temp_list_2:
					result_list.append( z )
		return result_list
	
	def ownrating( self, user ):
		rating						= 0
		try:
			rate					= self.rating_set.get( user=user )
			rating					= rate.rate
		except Rating.DoesNotExist:
			rating					= 0
		return rating
	
	def saleitem(self):
		saleitem = SaleItem.objects.get(product=self, onSale=True)
		return saleitem

	def __unicode__( self ):
		return self.title + " | " + self.type.__unicode__()
	__unicode__.short_description	= "Product"


"""
Sale items to control product (game) prices and availability.

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""
class SaleItem( models.Model ):
	price							= models.DecimalField( max_digits=7, decimal_places=2 )
	product							= models.ForeignKey( Product )
	onSale							= models.BooleanField( "On sale", default=True )

	def getPriceInEuros( self ):
		return u"%.2f \u20AC" % ( self.price, )

	def __unicode__( self ):
		return self.product.__unicode__() + u" | %.2f \u20AC" % ( self.price, )
	__unicode__.short_description	= "Sale item"


"""
Statistics about products (games).

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""
# Statistics: # of views only, because # of comment, # of sales, and average rating can be calculated?
class Statistic( models.Model ):
	product							= models.ForeignKey( Product )
	numberOfViews					= models.IntegerField( default=0 )
	
	def __unicode__( self ):
		return self.product.__unicode__() + " | %d view(s)" % ( self.numberOfViews, )
	__unicode__.short_description	= "Statistic"
		

"""
User's address.

Author(s): Markku Laine
"""
class Address( models.Model ):
	user							= models.ForeignKey( User )
	streetAddressLine1 				= models.CharField( "Street address line 1", max_length=100 )
	streetAddressLine2 				= models.CharField( "Street address line 2", max_length=100, blank=True )
	zipCode							= models.CharField( "ZIP code", max_length=10 )
	city 							= models.CharField( max_length=50 )
	state							= models.CharField( max_length=50, blank=True )
	country							= models.CharField( max_length=50, default="Finland" )

	class Meta:
		verbose_name_plural			= "Addresses"

	def __unicode__( self ):
		return self.user.first_name + " " + self.user.last_name + " (" + self.user.username + "), " + self.streetAddressLine1 + ( ", " + self.streetAddressLine2 if self.streetAddressLine2 is None else "" ) + ", " + self.zipCode + " " + self.city + ( ", " + self.state if self.state is None else "" ) + ", " + self.country
	__unicode__.short_description	= "Address"

		
"""
Comments related to products (games).

Author(s): Juha Loukkola and Kalle Saila
"""
class Comment( models.Model ):
	user 							= models.ForeignKey( User )
	published 						= models.DateTimeField( "Date published" )
	contents 						= models.TextField()
	commentsOn 						= models.ForeignKey( "self", null=True, blank=True )
	product							= models.ForeignKey( Product )

	def __unicode__( self ):
		return self.user.first_name + " " + self.user.last_name + " (" + self.user.username + ") | " + self.product.__unicode__() + " | " + self.contents
	__unicode__.short_description	= "Comment"
	
	def haschild(self):
		return Comment.objects.filter(commentsOn=self).count()


"""
Ratings related to products (games).

Author(s): Juha Loukkola and Kalle Saila
"""
class Rating( models.Model ):
	RATING_VERY_BAD					= 1
	RATING_BAD						= 2
	RATING_OKAY						= 3
	RATING_GOOD						= 4
	RATING_VERY_GOOD				= 5
	RATING_CHOICES	= (
		( RATING_VERY_BAD, "Very bad" ),
		( RATING_BAD, "Bad" ),
		( RATING_OKAY, "Okay" ),
		( RATING_GOOD, "Good" ),
		( RATING_VERY_GOOD, "Very good" ),
	)
	rate							= models.IntegerField( choices=RATING_CHOICES )
	user 							= models.ForeignKey( User )
	product							= models.ForeignKey( Product )

	def __unicode__( self ):
		return self.user.first_name + " " + self.user.last_name + " (" + self.user.username + ") | " + self.product.__unicode__() + " | " + str( self.rate )
	__unicode__.short_description	= "Rating"


"""
Shipping methods.

Author(s): Markku Laine
"""
class ShippingMethod( models.Model ):
	name							= models.CharField( max_length=50 )
	description						= models.TextField( blank=True )
	price							= models.DecimalField( max_digits=5, decimal_places=2 )
	onSale							= models.BooleanField( "On sale", default=True )

	def getPriceInEuros( self ):
		return u"%.2f \u20AC" % ( self.price, )

	def __unicode__( self ):
		return self.name + u" | %.2f \u20AC" % ( self.price, )
	__unicode__.short_description	= "Shipping method"


"""
User's orders.

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""
class Order( models.Model ):
	date							= models.DateTimeField()
	user 							= models.ForeignKey( User )
	delivered						= models.BooleanField()
	paid							= models.BooleanField()
	shippingMethod					= models.ForeignKey( ShippingMethod )
	address							= models.ForeignKey( Address )

	def getPriceInEuros( self ):
		return u"%.2f \u20AC" % ( self.price, )

	def getOrderItems( self ):
		return OrderItem.objects.filter( order=self )

	def getSubtotal( self ):
		subtotal					= 0
		orderItems					= OrderItem.objects.filter( order=self )

		for orderItem in orderItems:
			subtotal				= subtotal + ( orderItem.quantity * orderItem.saleItem.price )
		return subtotal

	def getSubtotalInEuros( self ):
		return u"%.2f \u20AC" % ( self.getSubtotal(), )

	def getTotal( self ):
		return self.getSubtotal() + self.shippingMethod.price

	def getTotalInEuros( self ):
		return u"%.2f \u20AC" % ( self.getTotal(), )

	def __unicode__( self ):
		return "#" + str( self.id ) + " | " + self.user.first_name + " " + self.user.last_name + " (" + self.user.username + ") | " + str( self.date )
	__unicode__.short_description	= "Order"


"""
Order items related to user's orders.

Author(s): Markku Laine, Juha Loukkola, and Kalle Saila
"""		
class OrderItem( models.Model ):
	saleItem						= models.ForeignKey( SaleItem )
	order							= models.ForeignKey( Order )
	quantity						= models.IntegerField( default=1 )

	def getPrice( self ):
		return self.quantity * self.saleItem.price

	def getPriceInEuros( self ):
		return u"%.2f \u20AC" % ( self.getPrice(), )
	
	def __unicode__( self ):
		return "%d" % self.id
	__unicode__.short_description	= "Order item"	

src/nintendo_gw_web_shop/templates/webshop/myaccount/account_details.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - My Account - Account Details{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-myaccount>span" ).addClass( "navi-selected" );

			// Highlight current page in the side navigation
			$( "#side-navi-myaccount-account-details>span" ).addClass( "side-navi-selected" );
			$( "#side-navi-myaccount-account-details" ).parent().append( $( "#side-navi-arrow" ) );		
			$( "#side-navi-arrow" ).show( "slide", { direction: "left" }, 500 );

			// Focus to the first input field
			$( "#id_first_name" ).focus();

			// Validate the form
			$( "#account-details-form" ).validate( {
				rules: {
					"first_name": {
						required: true,
						maxlength: 30
					},
					"last_name": {
						required: true,
						maxlength: 30
					},
					"email": {
						required: true,
						email: true,
						maxlength: 128
					}
				},
				messages: {
					"first_name": {
						required: "First name is required."
					},
					"last_name": {
						required: "Last name is required."
					},
					"email": {
						required: "E-mail address is required.",
						email: "Please enter a valid e-mail address."
		            }
				}
			} );
		} );	
	</script>				
{% endblock %}
{% block page-title %}My Account{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
		{% include "webshop/myaccount/side_navi_template.html" %}
	</div>
	<div id="main-content">
		<h3>Edit Account Details</h3>
		<form id="account-details-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				<tbody>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Update account details" /></td>
					</tr>
				</tbody>
			</table>
		</form>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/myaccount/address_book.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - My Account - Address Book{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-myaccount>span" ).addClass( "navi-selected" );

			// Highlight current page in the side navigation
			$( "#side-navi-myaccount-address-book>span" ).addClass( "side-navi-selected" );
			$( "#side-navi-myaccount-address-book" ).parent().append( $( "#side-navi-arrow" ) );		
			$( "#side-navi-arrow" ).show( "slide", { direction: "left" }, 500 );
		} );
	</script>				
{% endblock %}
{% block page-title %}My Account{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
		{% include "webshop/myaccount/side_navi_template.html" %}
	</div>
	<div id="main-content">
		<h3>Address Book</h3>
		{% load messages %}
		{% render_messages messages %}
		<table id="address-book-table">
			<thead>
				<tr>
					<th><a class="add" href="{% url webshop.views.address_book_new %}">Add a new address</a></th>
				</tr>
			</thead>
			<tbody>
				{% for address in addresses %}
					<tr>
						<td>
							<ul>
								<li class="bold">{{ first_name }} {{ last_name }}</li>
								<li>{{ address.streetAddressLine1 }}</li>
								{% if address.streetAddressLine2 != "" %}
									<li>{{ address.streetAddressLine2 }}</li>
								{% endif %}
								<li>{{ address.zipCode }} {{ address.city }}</li>
								{% if address.state != "" %}
									<li>{{ address.state }}</li>
								{% endif %}
								<li>{{ address.country }}</li>
							</ul>
							<form class="inline-form" action="{% url webshop.views.address_book_edit address_id=address.pk %}" method="get">
								<input type="submit" value="Edit" />
							</form>
							{% if addresses|length > 1 %}
								<form class="inline-form" action="{% url webshop.views.address_book_delete address_id=address.pk %}" method="get">
									<input type="submit" value="Delete" />
								</form>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/myaccount/address_book_delete.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - My Account - Address Book{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-myaccount>span" ).addClass( "navi-selected" );

			// Highlight current page in the side navigation
			$( "#side-navi-myaccount-address-book>span" ).addClass( "side-navi-selected" );
			$( "#side-navi-myaccount-address-book" ).parent().append( $( "#side-navi-arrow" ) );		
			$( "#side-navi-arrow" ).show( "slide", { direction: "left" }, 500 );
		} );
	</script>				
{% endblock %}
{% block page-title %}My Account{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
		{% include "webshop/myaccount/side_navi_template.html" %}
	</div>
	<div id="main-content">
		<h3>Delete Address</h3>
		{% load messages %}
		{% render_messages messages %}
		<table id="address-book-delete-table">
			<tbody>
				<tr>
					<td>
						<ul>
							<li class="bold">{{ first_name }} {{ last_name }}</li>
							<li>{{ address.streetAddressLine1 }}</li>
							{% if address.streetAddressLine2 != "" %}
								<li>{{ address.streetAddressLine2 }}</li>
							{% endif %}
							<li>{{ address.zipCode }} {{ address.city }}</li>
							{% if address.state != "" %}
								<li>{{ address.state }}</li>
							{% endif %}
							<li>{{ address.country }}</li>
						</ul>
						<form class="inline-form" action="{% url webshop.views.address_book_delete address_id=address.pk %}" method="post">
							{% csrf_token %}
							<input type="submit" value="Delete address" /> or <a href="{% url webshop.views.address_book %}">Cancel</a>
						</form>
					</td>
				</tr>
			</tbody>
		</table>		
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/myaccount/address_book_edit.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - My Account - Address Book{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-myaccount>span" ).addClass( "navi-selected" );

			// Highlight current page in the side navigation
			$( "#side-navi-myaccount-address-book>span" ).addClass( "side-navi-selected" );
			$( "#side-navi-myaccount-address-book" ).parent().append( $( "#side-navi-arrow" ) );		
			$( "#side-navi-arrow" ).show( "slide", { direction: "left" }, 500 );

			// Focus to the first input field
			$( "#id_streetAddressLine1" ).focus();

			// Validate the form
			$( "#address-form" ).validate( {
				rules: {
					"streetAddressLine1": {
						required: true,
						maxlength: 100
					},
					"streetAddressLine2": {
						maxlength: 100
					},
					"zipCode": {
						required: true,
						maxlength: 10
					},
					"city": {
						required: true,
						maxlength: 50
					},
					"state": {
						maxlength: 50
					},
					"country": {
						required: true,
						maxlength: 50
					}
				},
				messages: {
					"streetAddressLine1": {
						required: "Street address line 1 is required."
					},
					"zipCode": {
						required: "ZIP code is required."
					},
					"city": {
						required: "City is required."
					},
					"country": {
						required: "Country is required."
					}
				}
			} );		
		} );
	</script>				
{% endblock %}
{% block page-title %}My Account{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
		{% include "webshop/myaccount/side_navi_template.html" %}
	</div>
	<div id="main-content">
		<h3>Edit Address</h3>
		<form id="address-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				<tbody>
					<tr>
						<th>
							<label>Full name:</label>
						</th>
						<td class="bold">{{ first_name }} {{ last_name }}</td>
					</tr>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Update address" /> or <a href="{% url webshop.views.address_book %}">Cancel</a></td>
					</tr>
				</tbody>
			</table>
		</form>		
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/myaccount/address_book_new.html
{% extends "webshop/base_template.html" %}
{% block title %}Nintendo Game &amp; Watch Shop - My Account - Address Book{% endblock %}
{% block extra-scripts %}
	<script type="text/javascript">
		$( function() {
			// Highlight current page in the main navigation
			$( "#navi-myaccount>span" ).addClass( "navi-selected" );

			// Highlight current page in the side navigation
			$( "#side-navi-myaccount-address-book>span" ).addClass( "side-navi-selected" );
			$( "#side-navi-myaccount-address-book" ).parent().append( $( "#side-navi-arrow" ) );		
			$( "#side-navi-arrow" ).show( "slide", { direction: "left" }, 500 );

			// Focus to the first input field
			$( "#id_streetAddressLine1" ).focus();

			// Validate the form
			$( "#address-form" ).validate( {
				rules: {
					"streetAddressLine1": {
						required: true,
						maxlength: 100
					},
					"streetAddressLine2": {
						maxlength: 100
					},
					"zipCode": {
						required: true,
						maxlength: 10
					},
					"city": {
						required: true,
						maxlength: 50
					},
					"state": {
						maxlength: 50
					},
					"country": {
						required: true,
						maxlength: 50
					}
				},
				messages: {
					"streetAddressLine1": {
						required: "Street address line 1 is required."
					},
					"zipCode": {
						required: "ZIP code is required."
					},
					"city": {
						required: "City is required."
					},
					"country": {
						required: "Country is required."
					}
				}
			} );		
		} );
	</script>				
{% endblock %}
{% block page-title %}My Account{% endblock %}
{% block sort-bar %}{% endblock %}
{% block content %}
	<div id="side-navi">
		{% include "webshop/myaccount/side_navi_template.html" %}
	</div>
	<div id="main-content">
		<h3>New Address</h3>
		<form id="address-form" class="form" action="" method="post">
			{# Show validation errors #}
			{% if form.errors %}
				<div class="messages validation">
					<ul class="messages-list-validation">
						{% for key,value in form.errors.items %}
							{% for error in value %}<li>{{ error }}</li>{% endfor %} 
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% load messages %}
			{% render_messages messages %}
			{% csrf_token %}
			<table>
				<tbody>
					<tr>
						<th>
							<label>Full name:</label>
						</th>
						<td class="bold">{{ first_name }} {{ last_name }}</td>
					</tr>
					{% for field in form %}
						<tr>
							<th>
								<label for="{{ field.auto_id }}">
									{% if field.field.required %}
										<span class="required">{{ field.label }}:</span>
									{% else %}
										{{ field.label }}:
									{% endif %}
								</label>
							</th>
							<td>{{ field }}</td>
						</tr>
					{% endfor %}
					<tr>
						<th>&nbsp;</th>
						<td><input type="submit" value="Save address" /> or <a href="{% url webshop.views.address_book %}">Cancel</a></td>
					</tr>
				</tbody>
			</table>
		</form>		
	</div>
{% endblock %}

src/nintendo_gw_web_shop/templates/webshop/myaccount/side_navi_template.html
<div id="side-navi-arrow"></div>
<ul>
	<li><a id="side-navi-myaccount-account-details" href="{% url webshop.views.account_details %}"><span>account details</span></a></li>
	<li><a id="side-navi-myaccount-change-password" href="{% url webshop.views.change_password %}"><span>change password</span></a></li>
	<li><a id="side-navi-myaccount-address-book" href="{% url webshop.views.address_book %}"><span>address book</span></a></li>
	<li><a id="side-navi-myaccount-completed-orders" href="{% url webshop.views.completed_orders %}"><span>completed orders</span></a></li>
</ul>